In [1]:
!git clone https://github.com/Jarney903/Neural_Network_Charity_Analysis

Cloning into 'Neural_Network_Charity_Analysis'...
remote: Enumerating objects: 27, done.
remote: Counting objects: 100% (27/27), done.
remote: Compressing objects: 100% (20/20), done.
remote: Total 27 (delta 4), reused 24 (delta 4), pack-reused 0
Unpacking objects: 100% (27/27), done.

In [3]:
# Import our dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler,OneHotEncoder
import pandas as pd
import tensorflow as tf

# Import our input dataset
attrition_df = pd.read_csv('Resources/HR-Employee-Attrition.csv') #('Neural_Network_Charity_Analysis/Module Content/Resources/HR-Employee-Attrition.csv')
attrition_df.head()

ModuleNotFoundError: No module named 'tensorflow'

In [4]:
# Generate our categorical variable list
attrition_cat = attrition_df.dtypes[attrition_df.dtypes == "object"].index.tolist()

NameError: name 'attrition_df' is not defined

In [4]:
# Check the number of unique values in each column
attrition_df[attrition_cat].nunique()

Attrition         2
BusinessTravel    3
Department        3
EducationField    6
Gender            2
JobRole           9
MaritalStatus     3
Over18            1
OverTime          2
dtype: int64

In [5]:
# Create a OneHotEncoder instance
enc = OneHotEncoder(sparse=False)

# Fit and transform the OneHotEncoder using the categorical variable list
encode_df = pd.DataFrame(enc.fit_transform(attrition_df[attrition_cat]))

# Add the encoded variable names to the DataFrame
encode_df.columns = enc.get_feature_names(attrition_cat)
encode_df.head()

/usr/local/lib/python3.7/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)

,Attrition_No,Attrition_Yes,BusinessTravel_Non-Travel,BusinessTravel_Travel_Frequently,BusinessTravel_Travel_Rarely,Department_Human Resources,Department_Research & Development,Department_Sales,EducationField_Human Resources,EducationField_Life Sciences,...,JobRole_Research Director,JobRole_Research Scientist,JobRole_Sales Executive,JobRole_Sales Representative,MaritalStatus_Divorced,MaritalStatus_Married,MaritalStatus_Single,Over18_Y,OverTime_No,OverTime_Yes
0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,...,0.0,0.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0,1.0
1,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,...,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,1.0,0.0
2,0.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,1.0
3,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,...,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,1.0
4,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,1.0,0.0

In [6]:
# Merge one-hot encoded features and drop the originals
attrition_df = attrition_df.merge(encode_df,left_index=True, right_index=True)
attrition_df = attrition_df.drop(attrition_cat,1)
attrition_df.head()

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:3: FutureWarning: In a future version of pandas all arguments of DataFrame.drop except for the argument 'labels' will be keyword-only
  This is separate from the ipykernel package so we can avoid doing imports until

,Age,DailyRate,DistanceFromHome,Education,EmployeeCount,EmployeeNumber,EnvironmentSatisfaction,HourlyRate,JobInvolvement,JobLevel,...,JobRole_Research Director,JobRole_Research Scientist,JobRole_Sales Executive,JobRole_Sales Representative,MaritalStatus_Divorced,MaritalStatus_Married,MaritalStatus_Single,Over18_Y,OverTime_No,OverTime_Yes
0,41,1102,1,2,1,1,2,94,3,2,...,0.0,0.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0,1.0
1,49,279,8,1,1,2,3,61,2,2,...,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,1.0,0.0
2,37,1373,2,2,1,4,4,92,2,1,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,1.0
3,33,1392,3,4,1,5,4,56,3,1,...,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,1.0
4,27,591,2,1,1,7,1,40,3,1,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,1.0,0.0

In [7]:
# Split our preprocessed data into our features and target arrays
y = attrition_df["Attrition_Yes"].values
X = attrition_df.drop(["Attrition_Yes","Attrition_No"],1).values

# Split the preprocessed data into a training and testing dataset
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=78)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:3: FutureWarning: In a future version of pandas all arguments of DataFrame.drop except for the argument 'labels' will be keyword-only
  This is separate from the ipykernel package so we can avoid doing imports until

In [8]:
# Create a StandardScaler instance
scaler = StandardScaler()

# Fit the StandardScaler
X_scaler = scaler.fit(X_train)

# Scale the data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

At last, our data is preprocessed and separated and ready for modelling. For our purposes, we will use the same framework we used for our basic neural network:

**For our input layer**, we must add the number of input features equal to the number of variables in our feature DataFrame.

**In our hidden layers**, our deep learning model structure will be slightly different—we'll add two hidden layers with only a few neurons in each layer. To create the second hidden layer, we'll add another Keras Dense class while defining our model. All of our hidden layers will use the relu activation function to identify nonlinear characteristics from the input values.

**In the output layer**, we'll use the same parameters from our basic neural network including the sigmoid activation function. The sigmoid activation function will help us predict the probability that an employee is at risk for attrition.

In [9]:
# Define the model - deep neural net
number_input_features = len(X_train[0])
hidden_nodes_layer1 = 8
hidden_nodes_layer2 = 5

nn = tf.keras.models.Sequential()

# First hidden layer
nn.add(
    tf.keras.layers.Dense(units=hidden_nodes_layer1, input_dim=number_input_features, activation="relu")
)

# Second hidden layer
nn.add(tf.keras.layers.Dense(units=hidden_nodes_layer2, activation="relu"))

# Output layer
nn.add(tf.keras.layers.Dense(units=1, activation="sigmoid"))

# Check the structure of the model
nn.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense (Dense)               (None, 8)                 448

 dense_1 (Dense)             (None, 5)                 45

 dense_2 (Dense)             (None, 1)                 6

=================================================================
Total params: 499
Trainable params: 499
Non-trainable params: 0
_________________________________________________________________

In [10]:
# Compile the model
nn.compile(loss="binary_crossentropy", optimizer="adam", metrics=["accuracy"])

Now that Beks has her model defined and compiled, **it's time to train the model.**

In [11]:
# Train the model
fit_model = nn.fit(X_train,y_train,epochs=100)

Epoch 1/100
35/35 [==============================] - 1s 2ms/step - loss: 234.3910 - accuracy: 0.8212
Epoch 2/100
35/35 [==============================] - 0s 2ms/step - loss: 85.9737 - accuracy: 0.7405
Epoch 3/100
35/35 [==============================] - 0s 2ms/step - loss: 32.1795 - accuracy: 0.7196
Epoch 4/100
35/35 [==============================] - 0s 2ms/step - loss: 23.0527 - accuracy: 0.7260
Epoch 5/100
35/35 [==============================] - 0s 2ms/step - loss: 16.3040 - accuracy: 0.7260
Epoch 6/100
35/35 [==============================] - 0s 2ms/step - loss: 9.9292 - accuracy: 0.7405
Epoch 7/100
35/35 [==============================] - 0s 2ms/step - loss: 6.4823 - accuracy: 0.7196
Epoch 8/100
35/35 [==============================] - 0s 2ms/step - loss: 2.6490 - accuracy: 0.7250
Epoch 9/100
35/35 [==============================] - 0s 2ms/step - loss: 2.4084 - accuracy: 0.7414
Epoch 10/100
35/35 [==============================] - 0s 3ms/step - loss: 2.0425 - accuracy: 0.7559
Epoch 11/100
35/35 [==============================] - 0s 3ms/step - loss: 2.0518 - accuracy: 0.7423
Epoch 12/100
35/35 [==============================] - 0s 2ms/step - loss: 1.5646 - accuracy: 0.7423
Epoch 13/100
35/35 [==============================] - 0s 2ms/step - loss: 1.2721 - accuracy: 0.7704
Epoch 14/100
35/35 [==============================] - 0s 2ms/step - loss: 1.3528 - accuracy: 0.7514
Epoch 15/100
35/35 [==============================] - 0s 2ms/step - loss: 1.6363 - accuracy: 0.7532
Epoch 16/100
35/35 [==============================] - 0s 2ms/step - loss: 2.9914 - accuracy: 0.7223
Epoch 17/100
35/35 [==============================] - 0s 2ms/step - loss: 2.8402 - accuracy: 0.7341
Epoch 18/100
35/35 [==============================] - 0s 2ms/step - loss: 1.4726 - accuracy: 0.7495
Epoch 19/100
35/35 [==============================] - 0s 2ms/step - loss: 1.3578 - accuracy: 0.7486
Epoch 20/100
35/35 [==============================] - 0s 2ms/step - loss: 1.2062 - accuracy: 0.7477
Epoch 21/100
35/35 [==============================] - 0s 2ms/step - loss: 0.9240 - accuracy: 0.7677
Epoch 22/100
35/35 [==============================] - 0s 2ms/step - loss: 1.0603 - accuracy: 0.7659
Epoch 23/100
35/35 [==============================] - 0s 2ms/step - loss: 1.2007 - accuracy: 0.7641
Epoch 24/100
35/35 [==============================] - 0s 2ms/step - loss: 0.7849 - accuracy: 0.7922
Epoch 25/100
35/35 [==============================] - 0s 2ms/step - loss: 0.9416 - accuracy: 0.7750
Epoch 26/100
35/35 [==============================] - 0s 2ms/step - loss: 1.1901 - accuracy: 0.7505
Epoch 27/100
35/35 [==============================] - 0s 2ms/step - loss: 1.4399 - accuracy: 0.7423
Epoch 28/100
35/35 [==============================] - 0s 3ms/step - loss: 0.8950 - accuracy: 0.7877
Epoch 29/100
35/35 [==============================] - 0s 2ms/step - loss: 2.4773 - accuracy: 0.7287
Epoch 30/100
35/35 [==============================] - 0s 2ms/step - loss: 0.8412 - accuracy: 0.7695
Epoch 31/100
35/35 [==============================] - 0s 2ms/step - loss: 0.8969 - accuracy: 0.7731
Epoch 32/100
35/35 [==============================] - 0s 2ms/step - loss: 0.7455 - accuracy: 0.7840
Epoch 33/100
35/35 [==============================] - 0s 2ms/step - loss: 1.2738 - accuracy: 0.7686
Epoch 34/100
35/35 [==============================] - 0s 2ms/step - loss: 0.7562 - accuracy: 0.7985
Epoch 35/100
35/35 [==============================] - 0s 3ms/step - loss: 0.7798 - accuracy: 0.7822
Epoch 36/100
35/35 [==============================] - 0s 2ms/step - loss: 0.8206 - accuracy: 0.7831
Epoch 37/100
35/35 [==============================] - 0s 2ms/step - loss: 1.3345 - accuracy: 0.7541
Epoch 38/100
35/35 [==============================] - 0s 2ms/step - loss: 1.0506 - accuracy: 0.7750
Epoch 39/100
35/35 [==============================] - 0s 2ms/step - loss: 0.9020 - accuracy: 0.7786
Epoch 40/100
35/35 [==============================] - 0s 2ms/step - loss: 0.8802 - accuracy: 0.7750
Epoch 41/100
35/35 [==============================] - 0s 2ms/step - loss: 0.9596 - accuracy: 0.7740
Epoch 42/100
35/35 [==============================] - 0s 2ms/step - loss: 1.0567 - accuracy: 0.7650
Epoch 43/100
35/35 [==============================] - 0s 2ms/step - loss: 0.6730 - accuracy: 0.7913
Epoch 44/100
35/35 [==============================] - 0s 2ms/step - loss: 0.7918 - accuracy: 0.7895
Epoch 45/100
35/35 [==============================] - 0s 2ms/step - loss: 1.1533 - accuracy: 0.7604
Epoch 46/100
35/35 [==============================] - 0s 2ms/step - loss: 0.9120 - accuracy: 0.7967
Epoch 47/100
35/35 [==============================] - 0s 2ms/step - loss: 1.1725 - accuracy: 0.7595
Epoch 48/100
35/35 [==============================] - 0s 2ms/step - loss: 0.8919 - accuracy: 0.7940
Epoch 49/100
35/35 [==============================] - 0s 2ms/step - loss: 0.9940 - accuracy: 0.7613
Epoch 50/100
35/35 [==============================] - 0s 2ms/step - loss: 0.7084 - accuracy: 0.8149
Epoch 51/100
35/35 [==============================] - 0s 2ms/step - loss: 0.7145 - accuracy: 0.7940
Epoch 52/100
35/35 [==============================] - 0s 3ms/step - loss: 1.1900 - accuracy: 0.7759
Epoch 53/100
35/35 [==============================] - 0s 2ms/step - loss: 1.0321 - accuracy: 0.7632
Epoch 54/100
35/35 [==============================] - 0s 2ms/step - loss: 0.5866 - accuracy: 0.8113
Epoch 55/100
35/35 [==============================] - 0s 2ms/step - loss: 0.7454 - accuracy: 0.8013
Epoch 56/100
35/35 [==============================] - 0s 2ms/step - loss: 1.1818 - accuracy: 0.7686
Epoch 57/100
35/35 [==============================] - 0s 3ms/step - loss: 0.7020 - accuracy: 0.7940
Epoch 58/100
35/35 [==============================] - 0s 2ms/step - loss: 0.6129 - accuracy: 0.8076
Epoch 59/100
35/35 [==============================] - 0s 2ms/step - loss: 0.7557 - accuracy: 0.7985
Epoch 60/100
35/35 [==============================] - 0s 2ms/step - loss: 0.9013 - accuracy: 0.7913
Epoch 61/100
35/35 [==============================] - 0s 2ms/step - loss: 0.5871 - accuracy: 0.8321
Epoch 62/100
35/35 [==============================] - 0s 2ms/step - loss: 1.4128 - accuracy: 0.7704
Epoch 63/100
35/35 [==============================] - 0s 2ms/step - loss: 1.0848 - accuracy: 0.7495
Epoch 64/100
35/35 [==============================] - 0s 2ms/step - loss: 0.6180 - accuracy: 0.8040
Epoch 65/100
35/35 [==============================] - 0s 2ms/step - loss: 0.9069 - accuracy: 0.7759
Epoch 66/100
35/35 [==============================] - 0s 2ms/step - loss: 0.6705 - accuracy: 0.8022
Epoch 67/100
35/35 [==============================] - 0s 2ms/step - loss: 1.3038 - accuracy: 0.7731
Epoch 68/100
35/35 [==============================] - 0s 2ms/step - loss: 0.5372 - accuracy: 0.8258
Epoch 69/100
35/35 [==============================] - 0s 2ms/step - loss: 1.1369 - accuracy: 0.7568
Epoch 70/100
35/35 [==============================] - 0s 2ms/step - loss: 0.5587 - accuracy: 0.8240
Epoch 71/100
35/35 [==============================] - 0s 2ms/step - loss: 1.4734 - accuracy: 0.7577
Epoch 72/100
35/35 [==============================] - 0s 2ms/step - loss: 0.6802 - accuracy: 0.8013
Epoch 73/100
35/35 [==============================] - 0s 2ms/step - loss: 0.8863 - accuracy: 0.8113
Epoch 74/100
35/35 [==============================] - 0s 2ms/step - loss: 1.2588 - accuracy: 0.7641
Epoch 75/100
35/35 [==============================] - 0s 2ms/step - loss: 0.7451 - accuracy: 0.8103
Epoch 76/100
35/35 [==============================] - 0s 2ms/step - loss: 0.8520 - accuracy: 0.7868
Epoch 77/100
35/35 [==============================] - 0s 2ms/step - loss: 0.5628 - accuracy: 0.8312
Epoch 78/100
35/35 [==============================] - 0s 2ms/step - loss: 1.0753 - accuracy: 0.7831
Epoch 79/100
35/35 [==============================] - 0s 2ms/step - loss: 0.6476 - accuracy: 0.7949
Epoch 80/100
35/35 [==============================] - 0s 2ms/step - loss: 0.6731 - accuracy: 0.8149
Epoch 81/100
35/35 [==============================] - 0s 3ms/step - loss: 0.9611 - accuracy: 0.7813
Epoch 82/100
35/35 [==============================] - 0s 2ms/step - loss: 0.9518 - accuracy: 0.7886
Epoch 83/100
35/35 [==============================] - 0s 2ms/step - loss: 0.5134 - accuracy: 0.8267
Epoch 84/100
35/35 [==============================] - 0s 2ms/step - loss: 0.7876 - accuracy: 0.8131
Epoch 85/100
35/35 [==============================] - 0s 2ms/step - loss: 1.0619 - accuracy: 0.7568
Epoch 86/100
35/35 [==============================] - 0s 2ms/step - loss: 1.0806 - accuracy: 0.7650
Epoch 87/100
35/35 [==============================] - 0s 2ms/step - loss: 1.0428 - accuracy: 0.7813
Epoch 88/100
35/35 [==============================] - 0s 2ms/step - loss: 0.7365 - accuracy: 0.7995
Epoch 89/100
35/35 [==============================] - 0s 2ms/step - loss: 2.1233 - accuracy: 0.7341
Epoch 90/100
35/35 [==============================] - 0s 2ms/step - loss: 1.7517 - accuracy: 0.7486
Epoch 91/100
35/35 [==============================] - 0s 2ms/step - loss: 1.3524 - accuracy: 0.7722
Epoch 92/100
35/35 [==============================] - 0s 3ms/step - loss: 1.4850 - accuracy: 0.7477
Epoch 93/100
35/35 [==============================] - 0s 2ms/step - loss: 0.6105 - accuracy: 0.8176
Epoch 94/100
35/35 [==============================] - 0s 2ms/step - loss: 0.9286 - accuracy: 0.7877
Epoch 95/100
35/35 [==============================] - 0s 2ms/step - loss: 0.5162 - accuracy: 0.8294
Epoch 96/100
35/35 [==============================] - 0s 2ms/step - loss: 0.8018 - accuracy: 0.7731
Epoch 97/100
35/35 [==============================] - 0s 2ms/step - loss: 0.5824 - accuracy: 0.8267
Epoch 98/100
35/35 [==============================] - 0s 2ms/step - loss: 0.8290 - accuracy: 0.7840
Epoch 99/100
35/35 [==============================] - 0s 2ms/step - loss: 0.6509 - accuracy: 0.8212
Epoch 100/100
35/35 [==============================] - 0s 2ms/step - loss: 0.6109 - accuracy: 0.8212

In [12]:
# Evaluate the model using the test data
model_loss, model_accuracy = nn.evaluate(X_test,y_test,verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

12/12 - 0s - loss: 1.0506 - accuracy: 0.8587 - 187ms/epoch - 16ms/step
Loss: 1.0505766868591309, Accuracy: 0.8586956262588501